services:
  database:
    image: 'postgres:latest'
    #u need to specify the port and not keep it random
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_USER=myuser'
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
